### ISSUE TITLE
 mounting /dev/loop40

### ISSUE THREAD

**Issue by gartensofa** [ralph-irving/tcz-avahi#1]
Hello,
im trying to get avahi working on a raspi zero 1.3 with picoreplayer, but when installing dependencies as suggestet i get the following error:
`tc@piCorePlayer:~$ tce-load -i /mnt/mmcblk0p2/libavahi.tcz
mount: mounting /dev/loop40 on /tmp/tcloop/libavahi failed: Invalid argument
`
Should it work to just wget the given *.tcz-files and tce-load them?
any help would be greatly appreciated.

**Comment by ralph-irving** [comment]
You need to install all *.tcz and *.dep files from the tcz-avahi repository.  There are a lot of dependencies to the avahi packages.
Files need to be copied to the /mnt/mmcblk0p2/tce/optional folder then tce-load -i libavahi.tcz should work.

**Comment by gartensofa** [comment]
Thanks for your quick answer and sorry about forgetting to close this.
It works flawlessly when one manages to go over the whole readme ;-)
